apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provider
    app.kubernetes.io/part-of: spring-openfeign-demo
  name: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
        app.kubernetes.io/part-of: spring-openfeign-demo
    spec:
      containers:
        - image: spring-openfeign-demo-provider:0.0.1-SNAPSHOT
          name: provider
          env:
            - name: server.port
              value: "8080"
            - name: management.server.port
              value: "8081"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app.kubernetes.io/part-of: spring-openfeign-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: provider
